defaults: &defaults
  adapter: postgresql
  template: template0
  
test:
  <<: *defaults
  database: "swquilla_test"

development:
  <<: *defaults
  database: "swquilla_dev"

staging:
  <<: *defaults
  database: "swquilla_staging"

production:
  <<: *defaults
  database: "swquilla_production"